version: '3.3'
services:
  streaming-data-analyzer:
    build: ./
    container_name: streaming-data-analyzer
    image: streaming-data-analyzer
    env_file:
      - ./.env
    ports:
      - '3082:3082'
    # network_mode: 'host'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 4G
    extra_hosts:
      - 'kafka-1:10.0.3.50'
    restart: unless-stopped
