# Generated by Django 3.2.6 on 2021-09-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('pan', models.CharField(max_length=30)),
                ('uan', models.CharField(max_length=30)),
                ('Basic', models.CharField(max_length=30)),
                ('benefits', models.CharField(max_length=30)),
            ],
        ),
    ]
