# Generated by Django 3.2.6 on 2021-09-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='tax',
            field=models.CharField(default=10, max_length=30),
            preserve_default=False,
        ),
    ]
